import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset from a CSV file generated by the SQL query
df = pd.read_csv('retention_data.csv')

# Remove rows where retention_rate is not a valid value (e.g., NaN or inf)
df = df[pd.notnull(df['retention_rate']) & ~df['retention_rate'].isin([float('inf'), -float('inf')])]

# Convert 'month' to a datetime format to properly extract the month
df['month'] = pd.to_datetime(df['month'])

# Extract only the month and year in the format 'YYYY-MM'
df['month_label'] = df['month'].dt.strftime('%Y-%m')

# Sort the data by month to ensure the correct order in the plot
df = df.sort_values('month')

# Plot the retention rate over time using a bar plot
plt.figure(figsize=(12, 6))
sns.barplot(data=df, x='month_label', y='retention_rate', palette='Blues_d')

# Add title and labels with larger fonts
plt.title('Monthly Shop Retention Rate', fontsize=18)
plt.xlabel('Month', fontsize=14, labelpad=10)  # Ensure the 'Month' label is visible
plt.ylabel('Retention Rate (%)', fontsize=14, labelpad=10)

# Rotate x-axis labels for better readability
plt.xticks(rotation=45, ha='right', fontsize=12)
plt.yticks(fontsize=12)

# Show grid for better readability
plt.grid(True, axis='y')

# Adjust layout to ensure labels fit
plt.tight_layout()

# Save the plot as an image (optional)
plt.savefig('monthly_retention_rate_bar.png', dpi=300, bbox_inches='tight')

# Display the plot
plt.show()